FROM node:20-alpine

WORKDIR /app

RUN npm install -g nodemon

COPY package*.json ./
RUN npm install

COPY . .

# 개발 환경: 기본 포트 8000
ENV PORT=8000
ENV NODE_ENV=development
EXPOSE 8000

CMD ["npm", "run", "dev"]
