FROM node:20-alpine

WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY .env ./
COPY . .
RUN npm run build

# 온프레미스 환경: 포트 8989
ENV PORT=8989
ENV NODE_ENV=production
EXPOSE 8989

CMD ["node", "dist/index.js"]
