version: '3.8'

services:
  file-uploader-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8888:8888"
    volumes:
      # 소스 코드 변경을 실시간으로 반영
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=8888
    env_file:
      - .env
    restart: unless-stopped
    # 개발 환경에서는 로그를 더 자세히 출력
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3" 