apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  labels:
    app: {{ .Values.name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
    - name: https
      port: {{ .Values.service.httpsPort }}
      targetPort: {{ .Values.service.httpsPort }}
  selector:
    app: {{ .Values.name }}